### ISSUE TITLE
Add second analytics ID

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#122]
I got a request from the Google domains team to get `UA-49880327` added as a secondary analytics ID on the site so that they can track how the site is doing over time (this ID is different to adding them to the analytics account itself).

Some more info on: https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#multipletrackers

**Comment by zenorocha** [comment]
Are we still going to add this?

**Comment by zenorocha** [comment]
Closing this one due to its inactivity.
