### ISSUE TITLE
Add section for podcast /audio with Web Component content discussions

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#144]
Add a audio media section or subsection of 'presentations' page to reference audio clips of interviews and podcasts on Web Components.

**Comment by Nevraeka** [comment]
@zenorocha We could add this as a tags section similar to tools. we could also do a new right rail on the presentation section for audio/podcasting.  My questions would be what do we call it (audio or podcasts or something else) and where is the best place to add it?

**Comment by zenorocha** [comment]
@Nevraeka are there many episodes/podcasts talking about Web Components? Would you mind listing some of them?

If yes, what if we rename the `Presentations` page to `Talks` and create a new post for each episode using a `Podcast` tag?

**Comment by Nevraeka** [comment]
That might work. We may even be able to use the same template. Harder to find relevant images for audio though.

As for the quantity I know there was at least 2 in JSJ, 2 for the web ahead, maybe 2-3 for shop talk show. I found a few one offs and not to promote my podcast but we had at least 5 or 6 including our interview

**Comment by zenorocha** [comment]
Ok, let's see how many we have that way we can evaluate the best solution for it.

**Comment by Nevraeka** [comment]
Here is a starting point:

#### The Web Ahead by @jensimmons
- [Web Components with Peter Gasston](http://5by5.tv/webahead/66)
- [Componentizing the Web with Rob Dodson](http://5by5.tv/webahead/86)

#### Shop Talk Show by @chriscoyier
- [124: Rob Dodson](http://shoptalkshow.com/episodes/124-rob-dodson/)
- [141: Marcy Sutton](http://shoptalkshow.com/episodes/141-marcy-sutton/)

#### JavaScript Jabber by @cmaxw
- [Google Polymer with Rob Dodson and Eric Bidelman](http://devchat.tv/js-jabber/120-jsj-google-polymer-with-rob-dodson-and-eric-bidelman)

#### The Web Platform Podcast
- [21 : The X-Tag Project](http://thewebplatform.libsyn.com/21-the-x-tag-project)
- [20: Mozilla Brick, ‘UIKit’ for The Web](http://thewebplatform.libsyn.com/mozilla-brick-a-uikit-for-mobile-first)
- [14: Web Components Interop & Polymer](http://thewebplatform.libsyn.com/web-components-interop-and-polymer)
- [11: The Bosonic Project](http://thewebplatform.libsyn.com/the-bosonic-project)
- [9: Web Accessibility for JavaScript Components and Custom Elements](http://thewebplatform.libsyn.com/web-accessibility-for-javascript-components-and-custom-elements)
- [8: Exploring Dart & Polymer](http://thewebplatform.libsyn.com/exploring-dart-polymer)
- [5: The Web Components Community](http://thewebplatform.libsyn.com/the-web-components-community-helpful-resources)

Partial Episode Mentions
#### Treehouse Show 
- [Episode 104: Pixels, Web Components, The Hamburger Menu](http://teamtreehouse.com/library/the-treehouse-show/episode-104-pixels-web-components-the-hamburger-menu)

#### Lately in JavaScript Podcast
- [Building Better Web User Interfaces with Web Components](http://www.jsclasses.org/blog/post/66-Building-Better-Web-User-Interfaces-with-Web-Components--Lately-in-JavaScript-podcast-episode-46.html)

#### The Web Platform Podcast
- [25:  Showdown 2015](http://thewebplatform.libsyn.com/25-live-static-showdown-2015)
- [24: ServiceWorkers and High Performance Offline Apps](http://thewebplatform.libsyn.com/serviceworkers-and-high-performance-offline-apps)
- [17: The Famo.us vision of "Mobile First"](http://thewebplatform.libsyn.com/the-famous-vision-of-mobile-first)

- and of course all of the Polycasts

**Comment by Nevraeka** [comment]
I found a few in German to but I cannot say whether the content is good or not. (revision podcast)

**Comment by zenorocha** [comment]
We should only include the ones in english, otherwise articles and talks in other languages should be accepted as well and if we do that it's going to be a mess ;)

**Comment by Nevraeka** [comment]
Ah.....you are wise beyond your years. It's definitely a can of worms to tackle. Only english works for now

**Comment by zenorocha** [comment]
So the idea would be:

1. A new page called `Podcasts` using the same layout as `Articles` and `Presentations`.
2. All posts published here are external links to other podcasts.
3. No images are provided, just title, description, and link.
4. Authors are those who participated in the episode (including hosts).
5. In order to avoid noisy content, partial episode mentions should not be include.

How does that sound @Nevraeka?

**Comment by Nevraeka** [comment]
Good except - do we eliminate screencasts such as polycasts? Or perhaps add them to `presentations`

**Comment by zenorocha** [comment]
Our strategy for screencasts is to include it as an article and use the video as a complimentary thing.

Here are some examples for the [DevBytes series](https://www.youtube.com/watch?v=T5y_lmLngAk&list=PLOU2XLYxmsIJkA_W95NDrjdkk3dR6Jq4w) by @agektmr:
* http://webcomponents.org/articles/introduction-to-html-imports/
* http://webcomponents.org/articles/introduction-to-custom-elements/
* http://webcomponents.org/articles/introduction-to-template-element/
* http://webcomponents.org/articles/introduction-to-shadow-dom

**Comment by Nevraeka** [comment]
excellent!

**Comment by Nevraeka** [comment]
@zenorocha I'll post a PR ASAP

**Comment by Nevraeka** [comment]
@zenorocha - please review and let me know your thoughts. Thanks.

**Comment by Nevraeka** [comment]
One thing i didn't do was clutter the home page with another card. I felt this may not warrant its own home page real estate but I can easily add another few commits if we want it
