### ISSUE TITLE
Seems like part of documentation is missing

### ISSUE THREAD

**Issue by chrispesto** [webcomponents/webcomponents.github.io#178]
In the file https://github.com/webcomponents/webcomponents.github.io/blob/site/src/documents/polyfills/custom-elements.html.md (which is the GitHub version of the published page http://webcomponents.org/polyfills/custom-elements/) there's a line "Here's the imperative version of the previous example:" under the "document.registerElement()" heading.  There's also a later line "In the declarative and document.registerElement() example above" under the "Using a custom element" heading.  There isn't any previous declarative example on the page, however, or on the Introduction page it's linked from.

**Comment by zenorocha** [comment]
@addyosmani would you mind revisiting this one? Is it fixed already?

**Comment by zenorocha** [comment]
Closing this one due to its inactivity. Please send a PR if the error still exists @chrispesto.
