### ISSUE TITLE
Article explaining how to submit forms with Custom Elements

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#182]
Native `<form>` element is not aware of Shadow DOM so you need to use ajax or some nice element like [ajax-form](https://github.com/garstasio/ajax-form).

Might be useful to show some examples on how to accomplish that with some popular elements such as paper input elements.

Related:
* https://github.com/Polymer/core-input/issues/15
* https://groups.google.com/forum/#!topic/polymer-dev/NWPnWL0BJEU
* http://japhr.blogspot.com/2014/04/submitting-forms-with-polymer-elements.html
* https://blog.polymer-project.org/featured/2014/09/23/featured-002/
* http://stackoverflow.com/questions/24867107/paper-button-with-type-submit-within-form-doesnt-submit
* http://stackoverflow.com/questions/24615634/how-do-you-get-html5-inputs-to-validate-if-they-are-inside-polymer-web-component
* http://stackoverflow.com/questions/20115123/getting-html5-to-work-in-form-with-multiple-polymer-dart-components
* http://stackoverflow.com/questions/26155154/polymer-paper-input-form-checkvalidity
* http://stackoverflow.com/questions/24952217/how-to-submit-a-form-with-polymer
* http://stackoverflow.com/questions/23151817/polymer-manually-submitting-a-form
* https://www.polymer-project.org/docs/elements/paper-elements.html#paper-input

**Comment by zenorocha** [comment]
What do you think about that @garstasio? You would be perfect to write such article ;)

**Comment by zenorocha** [comment]
What do you think about that @rnicholus? You would be perfect to write such article ;)

**Comment by rnicholus** [comment]
@zenorocha Sounds like fun!  I'd be happy to write something up for webcomponents.org.  I need to finish up the last article in my "You Don't Need jQuery" series, and then I can start working on this.

**Comment by zenorocha** [comment]
That's awesome to hear ;)

**Comment by zenorocha** [comment]
Closing this one due to its inactivity. If you find some time, feel free to send a PR @rnicholus :)

**Comment by rnicholus** [comment]
So sorry that I didn't follow through with this yet @zenorocha. I have a few too many balls in the air right now. I'll keep this on my radar and try to put together an outline and start writing something up if I find some space in between my current commitments.

**Comment by zenorocha** [comment]
No problem @rnicholus, that's totally acceptable :)
