### ISSUE TITLE
Add Ele.io

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#201]
Add Ele.io to the discover section

**Comment by zenorocha** [comment]
Hey @Nevraeka,

I really like ele.io but I don't think it should be featured in the "Discover" since that area is more about searching and finding web components for your needs.

Unfortunately, I don't know which is the appropriate section for it. Any ideas @mbleigh?

**Comment by Nevraeka** [comment]
I think it would be appropriate for resources but the content would need to be a bit restructured since it only talks about boilerplates & generators.

**Comment by zenorocha** [comment]
We added a new box called "Tools" in that page yesterday, what about adding there? Could you send a PR?

http://webcomponents.org/resources/

**Comment by Nevraeka** [comment]
definitely. ASAP. Thank you @zenorocha

**Comment by Nevraeka** [comment]
cc @mbleigh @kevinchau
