### ISSUE TITLE
Should we list Web Components meetup groups?

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#206]
Meetup groups focused in Web Components are starting to appear more and more.

* [Paris](http://www.meetup.com/paris-webComponents/)
* [Los Angeles](http://www.meetup.com/Web-Components-LA/)
* [Washington](http://www.meetup.com/DC-Web-Components/)
* [Buenos Aires](http://www.meetup.com/Web-Components-BA/)
* [London](http://www.meetup.com/web-components-meetup/)

Do you guys think we should create a page to list them?

**Comment by sindresorhus** [comment]
:+1:

**Comment by randsonjs** [comment]
And create a card showing the last 5 meetups in home and a link below with `more meetups`. Like `tags` card.

**Comment by zenorocha** [comment]
I don't want to populate the homepage with too many cards but we can consider this later.

**Comment by zenorocha** [comment]
There are some Polymer meetups that can also be included:
* [Madrid](http://www.meetup.com/Madrid-Polymer-Group/)
* [Melbourne](http://www.meetup.com/Melbourne-Polymer-Meetup/)

**Comment by zenorocha** [comment]
One idea is to integrate [Meetup.com's API](http://www.meetup.com/meetup_api/) in this page. That way we can deliver some up to date informations.

The only problem is that we'll be limited to include only meetup.com user groups, do you guys see this as a problem?

**Comment by Nevraeka** [comment]
YES! :+1: [Polymer DC](http://www.meetup.com/polymer-dc/)

**Comment by brizabueno** [comment]
Thought of something like this, what do you think?

**Comment by brizabueno** [comment]
![meetup](https://cloud.githubusercontent.com/assets/5859819/5891653/a8f003c2-a489-11e4-84a2-664bda128e03.jpg)

**Comment by Nevraeka** [comment]
I love it. Would we have infoWindow on click of a meetup in the map? This fits nicely into the design as well. Great work

**Comment by zenorocha** [comment]
One more: [Polymer Mexico](http://www.meetup.com/PolymerMex/)

**Comment by zenorocha** [comment]
FYI @obetomuniz is working on this page based in @brizabueno's layout ;)

**Comment by obetomuniz** [comment]
@zenorocha :+1:

**Comment by Nevraeka** [comment]
Very exciting!

**Comment by zenorocha** [comment]
[DC Web Components](http://www.meetup.com/DC-Web-Components/)

**Comment by Nevraeka** [comment]
Any updates on this @obetomuniz ? It's an exciting addition

**Comment by Nevraeka** [comment]
Any updates on this? 

cc @zenorocha  @obetomuniz

**Comment by Nevraeka** [comment]
I can merge this but it would be nice to have a manual event template. Even after adding several meetups to the list, the WC meetups are so sporadic ATM as far (as posting new meetups on a regular basis). We have 2 tops in the queue, usually 0 or 1.  If anyone can volunteer to update the [PR for this](https://github.com/webcomponents/webcomponents.github.io/pull/226) with manual events, let me know. / @obetomuniz

**Comment by Nevraeka** [comment]
closing (this will be in the new redesign coming soon)
