### ISSUE TITLE
Add 'Server-less applications powered by Web Components' Presentation

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#208]
[https://www.youtube.com/watch?v=MdcD1rNkNLE](https://www.youtube.com/watch?v=MdcD1rNkNLE)
I'll have a PR for this ASAP

**Comment by zenorocha** [comment]
http://webcomponents.org/presentations/serverless-applications-powered-by-web-components/ ;)

**Comment by Nevraeka** [comment]
Cool. Thx
