### ISSUE TITLE
Better search box

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#211]
Now that more items have been added to our navigation bar we need a better solution for the search box, which takes a good amount of space.

![screen shot 2015-01-28 at 8 08 20 am](https://cloud.githubusercontent.com/assets/398893/5936586/e3876010-a6c4-11e4-809b-5a031443ba2c.png)

My suggestion is to keep using Google's custom search but with our own UI (like [HTML5 Rocks](http://www.html5rocks.com/en/) does), maybe something similar to @ebidel's `<material-search>` as seen on [Polymer Gmail](https://github.com/ebidel/polymer-gmail).

![search](https://cloud.githubusercontent.com/assets/398893/5936547/78e6a5d6-a6c4-11e4-8cd0-e2fe91d4cefb.gif)

**Comment by zenorocha** [comment]
Related to navigation https://github.com/webcomponents/webcomponents.github.io/commit/270b612efe3913eb3b49d98446f5dc7e8d448cf4

**Comment by Nevraeka** [comment]
what is the status on this @zenorocha ?
