### ISSUE TITLE
Add "Web Components – Drunk on the Panacea" talk

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#222]
- [ ] Slides
- [x] [Video](https://vimeo.com/110972839)

**Comment by zenorocha** [comment]
https://github.com/afabbro/drunk-on-the-panacea-web-components-oredev-2014/issues/1

**Comment by Nevraeka** [comment]
I sent a tweet to Angelina about the slides. I cannot find them anywhere. @zenorocha - were you able to get a link to them?

**Comment by robdodson** [comment]
this talk makes me sad :disappointed:

**Comment by zenorocha** [comment]
Closing this one due to its inactivity.
