### ISSUE TITLE
Screencasts Section

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#224]
Create a section under resources for short screencasts 5-10 minutes from the web components community leaders on simple "how to" items like styling a custom element, using templates, custom events, lifecycle events, etc. These would be similar to the type of videos egghead.io produces and would have related content links from the site to learn more (using tags presumably). What are your thoughts?

**Comment by robdodson** [comment]
+1, I know this show that would be perfect for it ;)

**Comment by Nevraeka** [comment]
@robdodson yeah...I heard about some hotshot from Cali doing some Polymer videos. Maybe we could get videos from that dude? ;p

**Comment by zenorocha** [comment]
What we did for all DevBytes videos from @agektmr [1] was creating an article using the video as an auxiliar resource. That way we can deliver a more complete content in that particular subject.

Is that something that you would be interested in @robdodson?

@Nevraeka do you know more resources that could benefit from a new section only focused in screencasts?

http://webcomponents.org/articles/introduction-to-html-imports/
http://webcomponents.org/articles/introduction-to-custom-elements/
http://webcomponents.org/articles/introduction-to-shadow-dom/
http://webcomponents.org/articles/introduction-to-template-element/

**Comment by robdodson** [comment]
At the moment our strategy is to embed the Polycast videos in the Polymer site docs in order to augment them:

https://www.polymer-project.org/docs/elements/icons.html

I don't think I'd be interested in writing a separate blog post reiterating the stuff from the docs. If only because it means updating things in two places when things change.

**Comment by Nevraeka** [comment]
I was more thinking of making a few but I am looking for a nice curation of these. I have mostly seen one-offs and meetup presentations (which can go in presentations or events)

**Comment by Nevraeka** [comment]
I think it's a great idea to add Polycasts the same way that devbytes id incorporated

**Comment by Nevraeka** [comment]
We can add polycasts to presentations. as well as others like this until we have enough content to justify a separation. Any opposition to this?

**Comment by Nevraeka** [comment]
Screencasts can be added to presentations as desired
