### ISSUE TITLE
Remove community card from homepage and create about page

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#230]
In the beginning it was important to highlight who was behind this project. Now that we've consolidated it, 
we could move this information to a different page.

My idea is to remove the community card from homepage and add a new page called "About", which would be found in the footer navigation under the "Community" label. This page would describe **what** is WebComponents.org, **why** we created and **who** is behind of it by fetching all GitHub contributors.

What do you think?

---

Related to #21 #83
Closes #47

**Comment by robdodson** [comment]
sgtm

**Comment by Nevraeka** [comment]
wrs (what Rob said)

**Comment by zenorocha** [comment]
We could also take this opportunity to rewrite our tagline and description.

> WebComponents.org - a place to discuss and evolve web component best-practices

---

> WebComponents.org is where pioneers and community-members of the Web Components ecosystem (like Polymer, X-tags, and other interested parties) document web components best practices so that others can follow the same path instead of needlessly striking out on their own.

**Comment by robdodson** [comment]
The current tagline doesn't bother me, it's nice and short which I like. Has there been discussion about needing to rename it?

**Comment by zenorocha** [comment]
One of the items mentioned in Q4 plans was *"More engaging text on About card"*, that's why I'm bringing this up.

**Comment by zenorocha** [comment]
Here's the visual proposal:

![teste](https://cloud.githubusercontent.com/assets/398893/6490025/f8120e1c-c281-11e4-98b5-29bbdd354a85.png)

**Comment by mateusortiz** [comment]
Cool, Leave it to me, I will do! I can do until tomorrow :smile:

**Comment by zenorocha** [comment]
An interesting component to use would be the [core-tooltip](https://www.polymer-project.org/docs/elements/core-elements.html#core-tooltip) showing the user's GitHub handle.

**Comment by Nevraeka** [comment]
:+1: I like it. The content needs some updating

**Comment by Nevraeka** [comment]
I like the usage of 'evolving' on the twitter account

**Comment by addyosmani** [comment]
Let's do more review before changing the tagline. 

The current one correctly captures what the site strives to achieve, but I'm sure it could be improved. What we need to keep in mind is that wc.org is now both home to community content and the official WC polyfills, so it serves a few different purposes. Would be great to keep that captured somehow.

**Comment by zenorocha** [comment]
Any news @mateusortiz?

**Comment by mateusortiz** [comment]
sorry for my delay @zenorocha :worried:

I had some problems but I will finish today

**Comment by Nevraeka** [comment]
@mateusortiz was this completed?
