### ISSUE TITLE
Add "Creating Container Components with Web Components and Angular"

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#233]
- [x] [Video](https://www.youtube.com/watch?v=AbunztfV5vU)
- [x] Slides

**Comment by Nevraeka** [comment]
https://docs.google.com/presentation/d/1SZ05jFRF9Rfsrn39z5-vdyLbY37XZGEgQfZ1uIOaEEo/pub?start=false&loop=false&slide=id.g6326acee8_1314

**Comment by Nevraeka** [comment]
- [] Add Kara Erickson's Google Plus

**Comment by Nevraeka** [comment]
@zenorocha - let me know if I should deploy this. Thx

**Comment by zenorocha** [comment]
Thanks @Nevraeka!
