### ISSUE TITLE
Add appropriate license

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#246]
Add appropriate permissions for anyone who uses the code. I personally prefer MIT but it seems BSD is the one we are using on other projects. 

**Example** : https://github.com/webcomponents/webcomponentsjs/blob/master/LICENSE.md

**Comment by zenorocha** [comment]
Hey @Nevraeka,

Have you seen this section? https://github.com/webcomponents/webcomponents.github.io#license

**Comment by Nevraeka** [comment]
nope. My apologizes
