### ISSUE TITLE
Add Interview Article w/ Travis Leithead & Apple/Webkit

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#248]
@travisleithead is working on the evaluation of Web Components for Microsoft Edge and Maciej Stachowiak is doing the same for Safari. Additionally @rniwa would be a good person to interview for e webkit in general on an implementation level if it fits into the interview format. Since Microsoft & Apple have the least support, it would be great to get the updates from them as an interview or 2 on the site.

**Comment by Nevraeka** [comment]
Should we break this out into 2 - 3 interviews and pull in @annevk / @wilsonpage & a google rep as well ?  cc @zenorocha @addyosmani

**Comment by addyosmani** [comment]
I know pretty much everyone cc'd has a lot on their plate atm. If they're open to doing interviews, I would probably break it out into individual pieces. You might want to touch on the recent work that went into converging on Shadow DOM V1 and so forth.

**Comment by Nevraeka** [comment]
I like the idea of one on one interviews on this. Best to do this after i/o and mozilla's internal conf in June

**Comment by Nevraeka** [comment]
@zenorocha , @robdodson or @addyosmani - any interest in helping w/ the interviews when things settle down?

**Comment by travisleithead** [comment]
I'm game for an interview. I'm not familiar with the format, etc. so any pointers would be nice :-)

**Comment by Nevraeka** [comment]
:+1: @travisleithead As an example check out the interview here - http://webcomponents.org/articles/interview-with-michael-bleigh/

Additionally, our all interviews are tagged w/ `interview` so here are all the current ones we have in the series -
http://webcomponents.org/tags/interview/

**Comment by Nevraeka** [comment]
@travisleithead I can do an interview with you at the end on the month. Are you around at that time?

**Comment by travisleithead** [comment]
Sorry to take so long to reply--yes that sounds great. The week of June 29th is open.

**Comment by Nevraeka** [comment]
Great! I'll email you a couple of times and details. Thanks @travisleithead

**Comment by Nevraeka** [comment]
@travisleithead sent you an email with details

**Comment by Nevraeka** [comment]
Set for Jul 8th

**Comment by Nevraeka** [comment]
Meeting today w/ Travis on Skype. I will close this issue shortly after I get a chance to put the article into markdown

**Comment by Nevraeka** [comment]
Added this. Ready for review by @zenorocha @travisleithead before I merge. Everything is in the interview branch. Do we need more transcription?

**Comment by Nevraeka** [comment]
Upon review, I need to remove my transcription and retain the same format (five questions/answers) as the other interviews with the exception of the audio & the title image. Will continue into next week on this. @travisleithead - when I am done summarizing the questions in the content, can you please verify the content?

**Comment by travisleithead** [comment]
You bet, just let me know when it's ready for review.

**Comment by Nevraeka** [comment]
@travisleithead thank you sir! :)

**Comment by Nevraeka** [comment]
I added paraphrased questions based on the discussion @travisleithead can you and @zenorocha review. I need to add links and proofread still

**Comment by travisleithead** [comment]
Probably messed it up, but sent you a pull request with feedback (from a detached head, this was kinda tricky)

**Comment by Nevraeka** [comment]
i got it. You were merging to the `site` branch so I'm going to close that PR. It's all good though. I just need to add links and a once over before @zenorocha reviews. Thanks Travis
