### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#261]
This is a question mostly. Do we feel we need a redesign. If so what would we improve in the UI/UX & content structure. I ask this because we have an about and contributions page being potentially being done as well as current sections started to get fairky large for their containers.

Our `authors.js` file is getting quite large and the resources page needs definitely needs to be redone as well.

What are your thoughts on this @addyosmani @zenorocha @brizabueno @randsonjs @goldoraf @obetomuniz @robdodson @PascalPrecht @eduardolundgren @cironunes @sindresorhus ?

**Comment by obetomuniz** [comment]
I think that's a great idea. I feel that the current design has limited the creation of some sections or improvement of existing ones. I also think that creating a redesign will help to use Web Components in construction.

**Comment by italowaxman** [comment]
This idea sounds like music to my ears. They can count on my help with regard to UX / UI and redesign. But so I can join in to the team after complete the other project https://customelements.io/

**Comment by PascalPrecht** [comment]
@Nevraeka Thanks for kicking this off! So I think a redesign is a huge thing to do. If we really decide we want to change it, we should start with a concept or at least brainstorm, what the key message is and what needs to be improved. And then there are so many things to play with e.g. Service Worker integration for offline stuff.

From a design perspective I'd like to see more room for the content. I really like material design, however, I don't think we should use it for webcomponents.org because people might get the feeling that it's yet another Polymer/Google thing, instead of something independent.

I would love to hear @brizabueno 's thoughts on this, since she made this awesome design that we currently have :)

**Comment by Nevraeka** [comment]
@PascalPrecht I love Material but agree with you on that point. This site is often referred to as THE resource for Web Components. We need a more scalable & extensible way to add content content.

**Comment by randsonjs** [comment]
This ideia is so great. I love Material Design too, so I agree with @PascalPrecht in use it for Webcomponents.org.

Waiting more thoughts on this :)

**Comment by PascalPrecht** [comment]
@randsonjs oh, maybe I put it not clearly enough. I actually wanted to say, that I *don't* think we should use material design, because people might refer it too much to Polymer.

**Comment by Nevraeka** [comment]
:+1: @PascalPrecht

**Comment by mateusortiz** [comment]
I also agree with @PascalPrecht, and I think the design is good, we just need to arrange some details, such as in the area of articles/content.

**Comment by zenorocha** [comment]
To be honest I'm comfortable with the current design. What may be slowing us down from implementing new stuff is DocPad.

Anyway, if you guys wants to propose something better, I'm totally open to that.

**Comment by addyosmani** [comment]
I'm :+1: with Zeno on this one. The current design isn't bad, but open to reviewing if there's something better proposed.

I'd rather see more effort poured into improving value offered by the site.

**Comment by Nevraeka** [comment]
@brizabueno did a fantastic job. The design from a visual perspective is working great and the flow is still working moderately well. I am starting to see that in many areas we struggle with content placement. Because of the vast amounts & types of content being produced I struggle with some questions like - Where do certain items belong? Why is this unclear where I put this item? Has anyone else experienced this?

Additionally, with the card structures, our content tends to be limited to how much content can be shown, which is expected (and beautiful). We have so many of these so close together that things are starting to get cramped and pages are getting taller in page height. 

The responsive nature of the site works great and that seems to work with the different content structures well. So I wouldn't change that approach. Using Web Components is optional for me due to the browser support tradeoffs but I am on the fence for that. 

It would be fun to see more ideas for UI and mostly for content strategy & flow. For me, a redesign is is more needed for the scalability of content and strategic content divisions. @addyosmani  IMO this would only help the 'improved value offered by the site'

**Comment by obetomuniz** [comment]
I also agree with @zenorocha that the current interface is good, but I believe that to improve the strategic proposal of WebComponents.org, a redesign is welcome. I think the best way for us would be to conduct a brainstorm to highlight the weaknesses of the current design and possible improvements.

**Comment by luanmuniz** [comment]
The last time i work in the project, DocPad was really a challenge! But i agree with @obetomuniz We should do a brainstorm or something like that to see what kind of content we want do implement and how is the best way to do it. With this kind of information we have more base to decide which part do we need to redesign or if you just need to change the tools.

**Comment by Nevraeka** [comment]
definitely resources. Probably the homepage as well. 

We have 2 issues for about about & contrib pages (1 each) that might make sense to combine & design out. Also I wonder if presentations & podcasts should be combined and rethought

**Comment by thiagotomasi** [comment]
Hi Guys,

Looking at the issues I saw some related to design and this discution about the entire redisign of the web site, how is this task? something was defined for the next steps?

If it is the consent of all, I have some ideas to organizing a project, either the redesign of the role website  if necessary, or even redign of some parts or compomentes, such as the search field.

Please, let me know if I can help if this!

**Comment by Nevraeka** [comment]
@PascalPrecht @obetomuniz @rands0n @mateusortiz @italowaxman @thiagotomasi @addyosmani - it's been a while since we looked at this issue. Should we close it out? Do a full redesign? Or update/redesign parts of the site? Why? Thanks in advance.

**Comment by Nevraeka** [comment]
this is happening now. Details to come in the next few weeks.
