### ISSUE TITLE
New assets page

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#271]
Since January 2014 we have this repo containing Web Components logos.

https://github.com/webcomponents/webcomponents-icons

Unfortunately it didn't have too much exposure and people still struggle to find high resolution images for blogposts, talks, etc.

I suggest we created a page on WC.org that gathers all that.

P.S.: Here's some inspiration: https://www.javascript.com/assets

**Comment by Nevraeka** [comment]
:+1:

**Comment by obetomuniz** [comment]
:heart: :+1:

**Comment by mateusortiz** [comment]
a simple mockup, what do you think:
![Imgur](http://i.imgur.com/BBK9Vil.png)

**Comment by Nevraeka** [comment]
@mateusortiz very nice. What do you think about using the card layouts for items ?

**Comment by obetomuniz** [comment]
@Nevraeka @zenorocha My idea for the page design is something like this >> http://webcomponents.org/swags 

I'll create a mockup.

o/

**Comment by mateusortiz** [comment]
@Nevraeka yeap i also thought about it

**Comment by Nevraeka** [comment]
+1 @obetomuniz & @mateusortiz

**Comment by obetomuniz** [comment]
@Nevraeka @zenorocha I think a design like this:

![screenshot-127 0 0 1 9778 2015-07-09 12-23-29](https://cloud.githubusercontent.com/assets/1680157/8599245/bafe6b5c-2635-11e5-9ff8-1645d628f424.png)

But, we need create a good introduction for this and adjust dimensions.

**Comment by Nevraeka** [comment]
:+1:

**Comment by obetomuniz** [comment]
@Nevraeka @zenorocha Before continue prototyping, three columns is good idea too, what do you think?

![screenshot-127 0 0 1 9778 2015-07-09 13-20-24](https://cloud.githubusercontent.com/assets/1680157/8600650/5c50b0e4-263d-11e5-8e70-17995c6e6edf.png)

**Comment by obetomuniz** [comment]
@Nevraeka I dont know about this font with all the logos, but we can create this at IconMoon using SVG sources

**Comment by zenorocha** [comment]
@obetomuniz no Polymer logo for now, let's start with Web Components assets only. We also need to display options for all the different sizes we provide.

@Nevraeka we do have a font icon: https://github.com/webcomponents/webcomponents-icons/tree/master/fonts

**Comment by zenorocha** [comment]
> Below you'll find some of the assets we've created for WebComponents.org. You may want these for a presentation, a blog post or whatever. All logos are high resolution with transparent backgrounds and are available in SVG, PNG, and Font formats.

3 columns are better.

**Comment by obetomuniz** [comment]
@zenorocha @Nevraeka This is the last update in my proposal.

![screenshot-127 0 0 1 9778 2015-07-09 15-34-23](https://cloud.githubusercontent.com/assets/1680157/8603718/6f4ce33a-2650-11e5-82ea-bffb1cadb917.png)

**Comment by Nevraeka** [comment]
@obetomuniz - why do we need multiple sizes for svg?

**Comment by obetomuniz** [comment]
@Nevraeka Hahahaha... Sizes for SVG? Each item of dimension are PNG file and "Get SVG" is an another item with the SVG file. The list of source files has a border and an hover effect that help separate the items. But, if this mockup don't are good, I'll need help for show all information, because we don't have components to put inside cards, like dropdown, simple lists, modal, etc.

**Comment by Nevraeka** [comment]
ah...now I see. I misunderstood. Thanks @obetomuniz

**Comment by zenorocha** [comment]
Looks nice @obetomuniz! Could you put a real color palette so we could see how it would look like? I believe there are less colors than what you put it there

**Comment by obetomuniz** [comment]
I put all colors that I found in the webcomponents.org, but I dont know what are our primary colors. The better way to find all colors of our colors palette is the designer that created this interface send these information for us. Can you contact the designer or you know tell me which are the colors? @zenorocha

**Comment by zenorocha** [comment]
#3A99D7, #FF5C03, #166497, #434A54

**Comment by obetomuniz** [comment]
:heart_eyes:

**Comment by obetomuniz** [comment]
@zenorocha @Nevraeka Can I send a PR? :dancer: 

"Our Color Palette" centralized
![screenshot-localhost 9778 2015-07-16 21-18-54](https://cloud.githubusercontent.com/assets/1680157/8738083/c8f8e824-2c00-11e5-8237-84b097736e7c.png)

"Our Color Palette" normal
![screenshot-localhost 9778 2015-07-16 21-22-05](https://cloud.githubusercontent.com/assets/1680157/8738084/c8fb945c-2c00-11e5-9e41-a23a8dc0af41.png)

**Comment by zenorocha** [comment]
Looks good! Go ahead :)

**Comment by zenorocha** [comment]
Rename "Our Color Palette" to "Color Palette" and make it centralized

**Comment by zenorocha** [comment]
http://webcomponents.org/assets/
