### ISSUE TITLE
Add Edge + Web Components articles

### ISSUE THREAD

**Issue by robdodson** [webcomponents/webcomponents.github.io#284]
http://blogs.windows.com/msedgedev/2015/07/14/bringing-componentization-to-the-web-an-overview-of-web-components/

and

http://blogs.windows.com/msedgedev/2015/07/15/microsoft-edge-and-web-components/

are golden!

**Comment by zenorocha** [comment]
Thanks @robdodson! Those were published yesterday already :)

* https://github.com/webcomponents/webcomponents.github.io/commit/43b892fe9074b700f8866bcf227d8c272039c4ad
* https://github.com/webcomponents/webcomponents.github.io/commit/9e86995f8f074f69d1327a576bf3c59f10997b56

**Comment by robdodson** [comment]
aw you guys are too quick for me! :dash:

**Comment by zenorocha** [comment]
:dancer:
