### ISSUE TITLE
[content] Add Polymer videos  

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#292]
Many screencasts have come out for Polymer and we need polycasts on here as well. When the videos for Polymer Summit are out we need to add them as well. I will use the issue to track these videos as being added to webcomponents.org

- [ ] Polycasts Season 1
- [ ] Polycasts Season 2
- [x] Polymer Summit Videos  (closed by [commit 2e73fda](https://github.com/webcomponents/webcomponents.github.io/commit/2e73fda1beda90b5b76ae383b99c775f79874b1d))
- [ ] Polymer Tutorials by [Ornge X](https://www.youtube.com/channel/UC8qkAEBGuiDmEuenK1IMw4A) (**needs review**)
- [ ] [LevelUpTuts Polymer Tutorials](https://www.youtube.com/playlist?list=PLLnpHn493BHGhoGAb2PRKzv4Zw3QoatK-) (**needs review**)

**Comment by zenorocha** [comment]
https://github.com/webcomponents/webcomponents.github.io/commit/2e73fda1beda90b5b76ae383b99c775f79874b1d

**Comment by Nevraeka** [comment]
:+1: Thank you @zenorocha . I was going to add all individually. Much better. :)

**Comment by Nevraeka** [comment]
content other than Polycasts is taking too long to review. closing
