### ISSUE TITLE
Incorrect link to content for Dr Axel Rauschmayer article

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#298]
[Current link](https://github.com/webcomponents/webcomponents.github.io/blame/site/src/documents/articles/what-happened-to-web-components.html.md#L6) needs to be set to [Axel's actual blog link](http://www.2ality.com/2015/08/web-component-status.html)

**Comment by Nevraeka** [comment]
/ @zenorocha

**Comment by zenorocha** [comment]
Ouch!

**Comment by Nevraeka** [comment]
Thanks for fixing @zenorocha :)
