### ISSUE TITLE
Usage of Logo in Blog Post

### ISSUE THREAD

**Issue by PatrickWalker** [webcomponents/webcomponents.github.io#314]
Hey,

Just requesting permission to use http://webcomponents.org/img/logo.svg within a post on web components for a not-for-profit engineering blog.

Would that be ok? We'll of course be referencing the webcomponents.org page

**Comment by zenorocha** [comment]
Sure, we even have a page with more details on that http://webcomponents.org/assets/ ;)

**Comment by PatrickWalker** [comment]
Thanks!

Note to self get better at navigating websites  :D
