### ISSUE TITLE
how to add podcast feed to podcatcher?

### ISSUE THREAD

**Issue by davidmaxwaterman** [webcomponents/webcomponents.github.io#317]
Hi,

I'm trying to use hpodder to download the selection of podcasts listed on your site:

<http://webcomponents.org/podcasts/>

It doesn't seem to understand the rss feed - does it actually contain any direct references to podcasts? Any ideas how to get it to work nicely?

Thanks.

**Comment by Nevraeka** [comment]
@davidmaxwaterman yes it should have references - although i'm not sure if podcatcher follows specific patterns that we are utilizing. What keys are missing and what is breaking in hpodder?

**Comment by davidmaxwaterman** [comment]
Well, I go to the above url and copy the rss url, then run :

```
[~]$ hpodder add http://feeds.feedburner.com/webcomponentsorg/podcasts
Podcast added:
    URL: http://feeds.feedburner.com/webcomponentsorg/podcasts
    ID: 16
```

I then :

```
[~]$ hpodder update 16
1 podcast(s) to consider

Get: 16                                                                        
100%                                                                   0 B/s 0s
[~]$ 
```

What do you think?

**Comment by Nevraeka** [comment]
use the `--debug` option. I wonder if the pointer keys are different than that of what itunes might use see [The Web Platform Podcast Feed](http://thewebplatform.libsyn.com/rss)

**Comment by davidmaxwaterman** [comment]
```
[~]$ hpodder --debug update 16
DB preparation complete
1 podcast(s) to consider

Beginning download of /home/davidmaxwaterman/.hpodder/feedxfer/4278f8a42d72fccab2d6d4344b312998
Get: 16 WebComponents.org                                                      
0% [16 0 B/1 B 0%]                                                     0 B/s 0scurl returned successfully; new size is Just 8964
 *** 16: Message on http://feeds.feedburner.com/webcomponentsorg/podcasts:     
Running: curl ["-A","hpodder v1.0.0; Haskell; GHC","-s","-S","-L","-y","60","-Y","1","--retry","2","-f","http://feeds.feedburner.com/webcomponentsorg/podcasts","-o","/home/davidmaxwaterman/.hpodder/feedxfer/4278f8a42d72fccab2d6d4344b312998"]

0%                                                                     0 B/s 0sDownload complete
Got feed
Added 0 new episodes
Got newpc from feed
Updated podcast on disk
Committed changes
100%                                                                   1 B/s 0s
[~]$ 
```

**Comment by Nevraeka** [comment]
I would check with the cli maintainer. To me, I see no direct issue on the feeds side. The output seems to indicate that everything just worked so....idk.

**Comment by davidmaxwaterman** [comment]
Yeah, that kind of why I thought there was no actual references to podcasts on there...just references to other references...or something (I hope you get what I'm trying to say).

Unfortunately, there is no maintainer for hpodder.... :/

Oh well, thanks anyway.
