### ISSUE TITLE
Component Kitchen doesn't have catalog anymore

### ISSUE THREAD

**Issue by fxedel** [webcomponents/webcomponents.github.io#319]
http://component.kitchen is referenced [here](webcomponents.github.io/src/documents/discover/componentkitchen.html) as a "Component catalog for a mainstream HTML audience", but they've [shut down their web component catalog](https://component.kitchen/blog/posts/were-shutting-down-our-web-component-catalog) last October. Should we edit the description or remove the whole link?

**Comment by zenorocha** [comment]
Yeah, you can send a PR to remove the file. Thanks @fxedel!
