### ISSUE TITLE
http://customelements.io/ seems empty in firefox nightly

### ISSUE THREAD

**Issue by anaran** [webcomponents/webcomponents.github.io#321]
css rule for body[unresolved] in
https://customelements.io/assets/vendor/webcomponentsjs/webcomponents-lite.js
matches.

Disabling the inline rules in firefox devtools makes the body visible and search functionality works.

I do have
 dom.webcomponents.enabled: true
set in firefox nightly.

**Comment by Nevraeka** [comment]
@anaran should we move this to the webcomponentsjs repo? It sounds like an issue that belongs there.

**Comment by anaran** [comment]
Something like https://github.com/webcomponents/webcomponentsjs/issues/570 ?
