### ISSUE TITLE
Migrate from DocPad to another static site generator

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#328]
### The Reasons for Migrating 
- `docpad` is no longer actively maintained
- modules with `docpad` are breaking in strange ways

[Metalsmith](http://www.metalsmith.io/) seems to be the favorite. We need something that isn't blog-centric since this site is not a blog. Thoughts?

**Comment by McPringle** [comment]
I prefer [Hugo](https://gohugo.io) which I use on several projects. It is really fast, actively maintained, has a good documentation, active community and is open source. The `docpad` files should be easy to convert. No, I won't work for Hugo, I just like using it… :-)

**Comment by Nevraeka** [comment]
I like hugo but most of our contributors aren't as knowledgable in Go as they are in JavaScript (as a generalization). It is very fast though. I like Middleman as well but we probably should use something closer to docpad workflow. Just my 2 cents. 

cc @zenorocha @obetomuniz @mateusortiz @robdodson

**Comment by Nevraeka** [comment]
We are in the midst of a redesign now. Closing.
