### ISSUE TITLE
X-Tag is supported by Microsoft, not Mozilla

### ISSUE THREAD

**Issue by rwhogg** [webcomponents/webcomponents.github.io#344]
The X-Tag library is supported by Microsoft, not Mozilla. I suspect that this is just a typo on http://webcomponents.org/

**Comment by treshugart** [comment]
It used to be supported by Mozilla, but the author moved to MS, hence the outdated info :)

**Comment by Nevraeka** [comment]
Updated and publishing the info now. Thank you for reporting this @rwhogg . It's a huge help and much appreciated
