### ISSUE TITLE
Add new polyfill projects

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#354]
Shadow DOM v1: shadydom v1, named-slots
Custom Elements v1: document-register-element, skate polyfill  (@treshugart ?)

**Comment by treshugart** [comment]
@Nevraeka https://github.com/skatejs/web-components is just a consolidation of a custom element polyfill and a shadow dom polyfill so consumers don't need to worry about which ones to include and what dependent polyfills they require. Up to you if you want to include it.

**Comment by Nevraeka** [comment]
closing for now
