### ISSUE TITLE
Add link to Web Components survey

### ISSUE THREAD

**Issue by vaadin-marcus** [webcomponents/webcomponents.github.io#358]
I spoke with Taylor about linking our Web Components and PWA survey from webcomponents.org 

The survey is at https://bit.ly/web-survey-2016 and will run until the end of October. 

We will do analysis and a report on the survey results. We'll give you access to the raw data and would love to also include your thoughts on the results in our report. 

Thanks, 
Marcus

**Comment by tjsavage** [comment]
@Nevraeka WDYT?

**Comment by Nevraeka** [comment]
we would need to create a quick place for it at or near the top of the page and make it mobile friendly as well. Do you have thoughts as to where to place this and how to display it? Maybe use a component? I can work on this Friday afternoon if anyone want s to help out. / @tjsavage @vaadin-marcus

**Comment by vaadin-marcus** [comment]
Near top of the page sounds good. Whether or not it needs its own component is really up to you and what  you think makes most sense. Thanks!

**Comment by Nevraeka** [comment]
I'll add this tomorrow afternoon

**Comment by Nevraeka** [comment]
It is live now...
https://github.com/webcomponents/webcomponents.github.io/commit/967adff44f31e8fb84362aca41c36e1dc24a1f39
