### ISSUE TITLE
Evaluate best way to integrate Bower search

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#5]
customelements.io appears to use a custom data source to power its Web Component search. i.e: https://github.com/customelements/customelements.io/blob/gh-pages/data/repos.json

Something better might be actually hooking up to the Bower registry backend/clone of it as per http://sindresorhus.com/bower-components/. It should now allow us to search across meta-data, e.g if a component says it is a web component.

From Sindre:

> The Bower search list now includes keywords by fetching bower.json keywords and falling back to package.json keywords. I also updated the site itself to include it and added support for searching for multiple keywords. You can now search for eg. web-components button

Would anyone like to try working on how we can get this into the site?

**Comment by Nevraeka** [comment]
@zenorocha I think this one can be closed
