### ISSUE TITLE
Homepage: improve FOUC before content displayed

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#57]
I'm seeing some FOUC on the homepage for ~1s before text is visible. Screenshot below:

![screenshot 2014-01-29 at 11 47 12 am](https://f.cloud.github.com/assets/110953/2029027/5aa5fdea-88db-11e3-921e-164501fe2e41.png)

Chrome version 32.0.1700.95. Not a show-stopper but worth taking a look at if time allows.

**Comment by zenorocha** [comment]
Closing this one due to its inactivity.
