### ISSUE TITLE
Article: Semantics

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#75]
There are two types of semantics. Author semantics and user semantics. Author semantics are things like `<div class=“alert”>…</div>` which provides guidances to the authors, whereas user semantics are things like `<h1>Heading</h1>` which expose extra machine-readable information to search engines, or assistive technology. 

Author semantics are great, but the user has to always come first.

It needs to be very clear that web components are not an agreed and standardised list of tags, they are all custom, and as such machines cannot be relied upon to understand the author’s intent. They should be used to wrap semantic tags, and ARIA implemented to ensure that user semantics remain in place and continue to give that great user experience.

On the Polymer side, we'll be publishing a comprehensive a11y guide soon but an article that focuses on a high-level view of semantics might be useful.

**Comment by zenorocha** [comment]
Closing this one due to its inactivity
