### ISSUE TITLE
Article: use native controls where possible?

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#76]
Web components need to solve problems that are not currently solved. We see often authors creating fake drop downs for behaviour or styling that they want, which is mostly already catered for in standard, native controls. 

It needs to be clear that native controls are preferred where possible, and that where there is a global problem (e.g. styling drop downs, tabbed boxes, details/summary widgets) these problems should be added to the standard spec (although web components would be great to polyfill!) rather than built thousands of times, and built wrong.

**Comment by zenorocha** [comment]
This is already covered by the Gold Standard, closing this one due its inactivity.  https://github.com/webcomponents/gold-standard/wiki/Declared-Semantics
