### ISSUE TITLE
Section for peer-reviewed Custom Elements

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#77]
Recently, a [number](http://aerotwist.com/blog/web-components-and-three-unsexy-pillars/) of [members](http://adactio.com/journal/6719/) of the front-end community expressed an interest in a community-driven path for vetting Web Components. Many have (rightly) voiced concerns about this new ecosystem of custom elements repeating the mistakes of past ecosystems, such as the jQuery plugin registry.  

In particular: lack of community-driven code reviews, poor re-use, lack of accessibility, documentation, performance benchmarking, internationalization and security audits as features core to their being. 

Mariead Buchan has also [raised concerns](http://www.emdeebeebee.com/golden_path) about:

* Lack of collaboration
* Increasing complexity
* Wasted effort
* Proliferation of code
* Lack of Re-use
* Fragmentation
* Lack of quality control

I wanted to focus on the lack of a platform for quality control and ways to promote the best of what we have to offer. These are paramount issues that we as a community do indeed to evolve solutions for if we're to repeat jQuery's issues of old.

## WebComponents.org recap

Over the past few months, I, @zenorocha  and members of the Web Components community (including representatives from Mozilla and Opera) have been working on a resource (yet unreleased) called WebComponents.org. The goals behind the project are to offer a community-driven resource for discussing and evolving best practices around components, highlighting educational content and eventually a Bower-driven gallery of elements which are community rated based on a number of quality factors.

We initially put together a set of [best practices](http://webcomponents.github.io/articles/web-components-best-practices/) that elements should target which do include accessibility and performance in mind. This list is undoubtedly going to improve over time and I welcome members of the community to help us hammer this out into a golden list of must-haves that can be used when we're building and reviewing elements. 

## A section for peer-reviewed elements

As Mariead calls out, one thing we're lacking is a platform for reviewing custom elements which, could potentially use our best practices list as a checklist. 

What I would like to propose is that WebComponents.org contains a section listing high-quality elements which are "blessed" by the community as being high-quality. Perhaps it could live at http://webcomponents.org/elements. These elements would be generally applicable enough to be re-used by others (e.g not a `<dancing-bear>` element, but sliders, buttons, menus, tabs etc).

The process for landing an element on the site could be as follows:

* The authors of these elements either submit a pull-request asking for a code review of their element or make a request for a review on their own repository. 
* A team of front-enders (who are knowledgable about performance, re-usability, accessibility, UX pattern design, security and so on) then review the source and provide feedback. This team can grow over time and contain those interested in peer reviewing.
* Once the element has passed review, it appears on the site. Developers who use it can be assured that what they are using is high-quality.

This solution factors in: 

* This system has a specific scope. We are not aiming to be a reviewer for every element in the eco-system and as such have reasonable ability to scale our efforts.
* The peer-review system not being a bottleneck to someone releasing something on GitHub without a review. It only appears as 'recommended' on the site once it has passed review.
* We have an existing list of psuedo-requirements (best practices) which we can use as a starting point for element review. Even if a developer doesn't want their element to appear on wc.org, they can use the list as a sanity check.

## Alternatives

If this sounds like a bad path to solving this issue, please let me know.

I've considered the idea of a third-party application/destination or a GitHub repository where those working on custom elements would submit their work for review, however I believe that in order to correctly scale we need to focus on elements that are going to be heavily used. Elements that are core and likely to be reused to build other elements.

**Comment by zenorocha** [comment]
Closing this one due to its inactivity
