### ISSUE TITLE
Article explaining how Responsive Design is applied to Web Components

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#78]
During EdgeConf someone asked about how Web Components play well with Responsive Design approaches ([watch his question and answer](https://www.youtube.com/watch?feature=player_detailpage&v=WVhBknHD5K8#t=1874)).

We could write an article that answers questions like "Should I include media queries breakpoints inside my element?" and "How can I create an element that works in any screen size".

Is any of you interested in writing an article about it? @stopsatgreen @robdodson @sole @mathiasbynens @csuwildcat @potch @brucelawson

**Comment by Nevraeka** [comment]
:+1: Time has past on this since the last comment. We should reevaluate a new article. Any new thoughts on this?

**Comment by zenorocha** [comment]
Closing this one due to its inactivity.
