### ISSUE TITLE
Article explaining how i18n works in Web Components 

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#79]
There are lots of discussions around i18n + Web Components (like this one in [Polymer's mailing list](https://groups.google.com/forum/#!topic/polymer-dev/kBxj2jA0CTk)).

@passy, since you've been working with i18n a lot lately, do you have interest in writing an article about this topic on WC.org?

**Comment by Nevraeka** [comment]
@eee-c @passy @eisenbergeffect do any of you have bandwidth to write an article around i18n + Web Components?

**Comment by zenorocha** [comment]
@ebidel wrote a [i18n component](https://github.com/ebidel/i18n-msg) for santa tracker. He might be too busy because of Polymer 0.8 but it's probably a good starter point.

**Comment by Nevraeka** [comment]
It's an important topic so I would not want to close this one until we have at least a basic intro article. @davismj has an article he's been writing for Aurelia as well

**Comment by zenorocha** [comment]
+1 @Nevraeka

**Comment by davismj** [comment]
I'm not entirely sure where what the Aurelia team is up to fits in with your need here. Aurelia allows for DOM extension, including custom elements. Additionally, i18n support as a first-class citizen in Aurelia is being actively discussed. This may or may not be of interested to the WebComponents team, but I'm definitely open to further dialog. Thoughts?

**Comment by Nevraeka** [comment]
@davismj the article for this issue would need to have direct context with how to use i18n with Web Components. So it depends if your post actually focuses on those 2 pieces as a primary importance. If not then it's probably not a great fit for this project. Either way I want to read it so let us know in the gitter channel for Aurelia :)

**Comment by davismj** [comment]
Will do. :)

**Comment by zenorocha** [comment]
Closing this one due to its inactivity. If you find some time, please feel free to send a PR @davismj :)
