### ISSUE TITLE
Article explaining how to do Unit Testing in Custom Elements

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#80]
This is another topic that is pretty important to cover.

I noticed that most Polymer/X-Tag elements contains unit tests. So maybe we can get someone from these teams to write about it. What do you think @addyosmani @robdodson @potch @sole @csuwildcat?

**Comment by Nevraeka** [comment]
With the standardization of `webcomponents-tester` I think we do this now. @addyosmani - I would love to collaborate on an article for my own selfish desire to be better at testing components. If not, one of us could do it on our own. Let me know :)

**Comment by addyosmani** [comment]
I wrote https://www.polymer-project.org/0.5/articles/unit-testing-elements.html after my original comment which tried to walk through web-component-tester. We could definitely use a 1.0 update to this for the Polymer site, but it might make more sense there vs wc.org. That said, I'd also be interested in seeing a separate Custom Elements + WCT tutorial at some point :)

**Comment by zenorocha** [comment]
Closing this one for now since there was no action since last year, if there's anyone up to do that please send a PR.
