### ISSUE TITLE
Flesh out the best practices guide

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#82]
The community have recently re-enforced their desire to see web components also tackle issues around accessibility, performance, testing and so forth. Whilst these are generally good for any form of component authorship we should polish up the existing guide to ensure we're not missing anything.

I've also noticed some syntax errors in the guide that need some fixing. I'll update the guide this week or next based as time allows.

**Comment by Nevraeka** [comment]
also check out our [Golden Standard repository](https://github.com/webcomponents/gold-standard)

**Comment by zenorocha** [comment]
Closing this one due to its inactivity
