### ISSUE TITLE
Link to venues for discussions

### ISSUE THREAD

**Issue by addyosmani** [webcomponents/webcomponents.github.io#83]
We recently setup #webcomponents over on IRC and have also been engaging with the community (albeit a little) on the Web Components Google group. It may be worth figuring out where we can mention these on the site.

**Comment by Nevraeka** [comment]
Any updates?

**Comment by Nevraeka** [comment]
Also 
- [Polymer Google Community](https://plus.google.com/communities/115626364525706131031)
- [Web Components Google Community](https://plus.google.com/communities/113308949212527149307)
- [Polymer Google Group](https://groups.google.com/forum/#!forum/polymer-dev)
- [Web Components on LinkedIn](https://www.linkedin.com/groups?home=&gid=5187485)

**Comment by Nevraeka** [comment]
no updates have been posted for over a year. closing this issue
