### ISSUE TITLE
Make it easier to identify what is content authored by us and what is external

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#99]
> "In the articles section of the site, it's a little unclear what is hosted by us and what is off-site. We have a mix of them. Is there a way to more clearly denote articles written and hosted on wc.org and offsite content?"

**Comment by faelaphoenix** [comment]
The problem also inserting the icon would be on accessibility, it would be good also described in the alt that is an external / internal link. An alternative would be good to think through different colors for internal / external links.

**Comment by Nevraeka** [comment]
closing this because it hasn't had an update in over a year. Let me know if we should revisit.
